name: Gradle generate and publish javadocs

on:
  workflow_call:
    inputs:
      directory:
        description: 'directory to javadoc'
        default: 'build/docs/javadoc'
        required: false
        type: string
      java_version:
        type: string
        default: '25'
    secrets:
      JORISG_REPO_USERNAME:
        required: false
      JORISG_REPO_PASSWORD:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'temurin'

      - name: Gradle Javadoc
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc
        env:
          ORG_GRADLE_PROJECT_JorisgUsername: ${{ secrets.JORISG_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_JorisgPassword: ${{ secrets.JORISG_REPO_PASSWORD }}

      - name: Deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: javadocs
          folder: ${{ inputs.directory }}
